apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/nginx
        ports:
        - containerPort: 80
